version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 327568102787.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - docker build -t braintask-app .
      - docker tag braintask-app:latest 327568102787.dkr.ecr.ap-south-1.amazonaws.com/braintask-app:latest
  post_build:
    commands:
      - docker push 327568102787.dkr.ecr.ap-south-1.amazonaws.com/braintask-app:latest
