apiVersion: apps/v1
kind: Deployment
metadata:
  name: brainapp-deployment
  labels:
    app: brain-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brain-app
  template:
    metadata:
      labels:
        app: brain-app
    spec:
      containers:
        - name: myapp-container
          image: 327568102787.dkr.ecr.ap-south-1.amazonaws.com/braintask-app:latest
          ports:
            - containerPort: 80